### PR TITLE
Bump 'python_requires' to 3.5

### PR DESCRIPTION
**Pull request by michael-k**
Bumping to 3.4 allows replacing `os.path` with [`pathlib`](https://docs.python.org/3/library/pathlib.html), but since Python 3.4 reached its [EOL on 2019-03-18](https://www.python.org/dev/peps/pep-0429/) `python_requires` should be bumped to 3.5.

I've updated `.travis.yml` to run the tests against both ends of the required Python versions, ie. 3.5 and 3.7.

This PR also updates the classifiers and marks the wheel as no longer being universal (because it's not compatible with Python 2; see https://pypi.org/project/formica-cli/#files).

### CODE REVIEW

**Comment by flomotlik** [comment]
@michael-k awesome. Any idea why the build fails there?

**Comment by michael-k** [comment]
[assert_called_once](https://docs.python.org/3/library/unittest.mock.html#unittest.mock.Mock.assert_called_once) was added in Python 3.6.  I'll update the PR to address this.

**Comment by flomotlik** [comment]
Sorry for not answering yet, next week out of a project and jumping into open source work again. Thanks for the PR again

**Comment by flomotlik** [comment]
After reviewing the change I'm not sure if you intended to bring the change from os.path to pathlib already into the PR or if this should be done in a separate PR? Sorry for the delayed answer, was deep in a project until recently.

**Comment by michael-k** [comment]
> After reviewing the change I'm not sure if you intended to bring the change from os.path to pathlib already into the PR or if this should be done in a separate PR?

separate PR

The main focus here is to drop support for Python versions that reached their EOL.  Taking advantage of the then available features (eg. pathlib) is something for future PRs.  I generally try to keep changes as small as possible to ease reviews.

**Comment by flomotlik** [comment]
I pushed it to 3.6 in another PR now and added 3.6 as well. Since 3.5 is in security updates only mode I skipped that (even though it should be working with formica) as we don't need the whole testing complexity then. Thanks for the follow up!

**Comment by michael-k** [comment]
Normally maintainers are a bit hesitant when it comes to dropping python versions. ;)
3.6 is great. f-strings, variable annotations, …

**Comment by flomotlik** [comment]
Waited so long to drop 2.X, now I just want to stay up to date :). Also since this is tooling for cloud infrastructure its more likely that its irrelevant for people what the python version is (at least in my experience working on customer projects). Rarely do they even use python or just very simple Lambdas where its always 3.6 or 3.7 anyway (or running in Docker containers).

**Pull request closed without merging**
